name: flutter_facebook_auth
description: The easiest way to add facebook login to your flutter app. Feature includes getting user information, profile picture and more. This plugin also supports Web and macOS.
version: 5.0.7
homepage: https://github.com/darwin-morocho/flutter-facebook-auth

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_facebook_auth_platform_interface:
    git:
      url: https://github.com/blablaconnectcodemagic/flutter-facebook-auth/
      path: flutter_facebook_auth_platform_interface
  # flutter_facebook_auth_platform_interface:
  #   path: ../facebook_auth_platform_interface
  flutter_facebook_auth_web:
    git:
      url: https://github.com/blablaconnectcodemagic/flutter-facebook-auth/
      path: flutter_facebook_auth_web
  # flutter_facebook_auth_web:
  #   path: ../facebook_auth_web

  facebook_auth_desktop:
   git:
      url: https://github.com/blablaconnectcodemagic/flutter-facebook-auth/
      path: facebook_auth_desktop
    # path: ../facebook_auth_desktop

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  plugin:
    platforms:
      android:
        package: app.meedu.flutter_facebook_auth
        pluginClass: FlutterFacebookAuthPlugin
      ios:
        pluginClass: FlutterFacebookAuthPlugin
      web:
        default_package: flutter_facebook_auth_web
      macos:
        default_package: facebook_auth_desktop


